### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pavs** [5310/netdata-plugin-ping#1]
Hello. I couldn't get it to work. I mean I got it to install and run command from the command line like this:

`/usr/libexec/netdata/plugins.d/ping.plugin 10 google.com github.com` and I turned it on on netdata.conf but I don't see any graph. Am I missing something?

**Comment by 5310** [comment]
Sorry for the really late reply. Being unsure as to where to include the graph I put it under the Network Interfaces category, alongside graphs for eth0, etc. Can you find it there?

**Comment by pavs** [comment]
Hey, Thanks for the reply.

No, I don't see it under Network Interfaces. Maybe I have set it up wrong in configuration?
In `/etc/netdata/netdata.conf` under plugin:

```
        # node.d = yes
        # python.d = yes
        # ping = yes
```

For plugins option:

```
[plugin:ping]
        # update every = 1
        # command options = ping.plugin 10 google.com github.com
```

Even if I keep the command options empty, it doesn't work. Maybe I am doing something wrong?

**Comment by 5310** [comment]
Ah, it looks like you still have the line that enables the plugin commented out, as well as the configs.

Firstly, uncomment the following:

```
        # node.d = yes
        # python.d = yes
        ping = yes
```

And then, uncomment the configs too. Customize the update interval as you want. And for the command option, just input the hostnames you want pinged since Netdata supplies the update-interval value anyway:

```
[plugin:ping]
        update every = 10
        command options = google.com github.com
```

**Comment by pavs** [comment]
Silly me. I thought since the other plugins being used also have hash in front of them, that's how it worked.

I followed your suggestions and restarted netdata however, it's still not working for me.

```
/usr/libexec/netdata/plugins.d$ ls -lh /usr/libexec/netdata/plugins.d/
total 196K
-rwxr-xr-x 1 root root  10K Aug 22 15:23 alarm-email.sh
-rwxr-xr-x 1 root root 107K Aug 22 15:23 apps.plugin
-rwxr-xr-x 1 root root 2.4K Aug 22 15:23 cgroup-name.sh
-rwxr-xr-x 1 root root 1.2K Aug 22 15:23 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 root root  20K Aug 22 15:23 charts.d.plugin
-rwxr-xr-x 1 root root 2.4K Aug 22 15:23 loopsleepms.sh.inc
-rwxr-xr-x 1 root root  11K Aug 22 15:23 node.d.plugin
lrwxrwxrwx 1 root root   53 Aug 11 00:36 ping.plugin -> /usr/lib/node_modules/netdata-plugin-ping/ping.plugin
-rwxr-xr-x 1 root root  19K Aug 22 15:23 python.d.plugin
-rw-r--r-- 1 root root 7.3K Aug 22 15:23 README.md
-rwxr-xr-x 1 root root 2.8K Aug 22 15:23 tc-qos-helper.sh
```

![screen shot 2016-08-22 at 4 48 58 pm](https://cloud.githubusercontent.com/assets/3807064/17852316/7d38391a-6888-11e6-9df6-569e58b0530b.png)

**Comment by 5310** [comment]
Did you restart Netdata after the changes?

**Comment by pavs** [comment]
Hi I think I found the problem but I don't know the solution yet. Seems like a netdata or my installation issue, not with the plugin.

When I start netdata using `sudo /usr/sbin/netdata` and goto `<ipaddress>:<port>/netdata.conf` it loads the default configuration instead of the configuration I changed in `/etc/netdata/netdata.conf`. Same happens even if I specifically mention config file during runtime `sudo /usr/sbin/netdata -c /etc/netdata/netdata.conf` I am thinking about reinstalling netdata from scratch and see if it fixes the problem.

**Comment by pavs** [comment]
Hey, Thanks for being patient with me, turns out it was an issue with my local nodejs install and file permission. I finally got it working. If you are interested you can check out the discussion here:
https://github.com/firehol/netdata/issues/819

![screen shot 2016-08-23 at 10 26 12 pm](https://cloud.githubusercontent.com/assets/3807064/17900414/132f6ed6-6981-11e6-8d84-a4b647c72089.png)

**Comment by 5310** [comment]
Oops, I missed over another cycle on this issue. Sorry about that! But I'm sure glad it's resolved. 

Thank you for the reference issue too, now I understand Netdata default configs a bit more. (I must admit it's still kinda confusing: Even on my system localhost:19999/netdata.conf gets me a file that's different from my config, but it still works as I expect. My custom options show up, but are commented there! So weird.)

I also sympathise that your pings to github are are high and lossy as mine!

**Comment by pavs** [comment]
Haha. The similar GitHub latency is probably due to the fact that we are both from the same part of the world, speak the same language, but we live a couple of 100 miles apart with an international border between us. :)

**Comment by 5310** [comment]
And yet, you have nice smooth low latencies to Google, whereas my pings to
8.8.8.8 looks pretty much the same as your GitHub!

Buy then, that's just my unfortunate neighborhood... :D
